# Step 1: Build stage
FROM node:18-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .
RUN npm run build

# Step 2: Production stage
FROM node:18-alpine

WORKDIR /app

# Copy required files from builder
COPY --from=builder /app/package.json ./
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/next.config.ts ./

# Expose port
EXPOSE 3000

# Set env to production
ENV NODE_ENV=production

# Start the app
CMD ["npm", "run", "start"]
