name: Dev Pipeline

on:
  push:
    branches:
      - dev

env:
  AWS_REGION: us-east-1

jobs:
  dev-stage:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init and Apply (Dev)
        working-directory: ./Terraform
        run: |
          cd terraform/Environments/Development
          terraform init
          terraform apply --auto-approve