name: Frontend Dev Pipeline
description: CI/CD pipeline for the development NextJS Frontend application

on:
  push:
    branches:
      - dev
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-dev.yml'

jobs:
  Frontend:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest
    environment: dev

    env:
      NEXTJS_ECR_URL: ${{ secrets.NEXTJS_ECR_URL }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
    
      - name: Login to Amazon Flask ECR repo
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{secrets.ECR_REGISTRY}}
          
      - name: Build and Push Next.js App
        run: |
          docker build -t nextjs-app ./frontend
          docker tag nextjs-app:latest $NEXTJS_ECR_URL:latest
          docker push $NEXTJS_ECR_URL:latest
